//
// Created by Ludwig on 2017-06-22.
//

#ifndef MINER_STAGEIDENTIFICATION_H
#define MINER_STAGEIDENTIFICATION_H

const int STAGE_COUNT = 3;

enum STAGE_ID {
    MENU, MINE, CASINO
};

#endif //MINER_STAGEIDENTIFICATION_H
